POST http://localhost:3000/patients
Content-Type: application/json

{
  "name": "Danish",
  "email": "011a111ss22111nsarida1ak1s2sssssFSDSDFS22afsdnish78611as114@gmail.com",
  "address": "Mumbai",
  "dateOfBirth": "2003-06-17",
  "registeredDate": "2025-11-20"
}