POST http://localhost:3000/patients
Content-Type: application/json

{
  "name": "Danish",
  "email": "danis12sh@gmail.com",
  "address": "Mumbai",
  "dateOfBirth": "2003-06-17",
  "registeredDate": "2025-11-20"
}